.so fass/1990/script/bulkmacr.t
.bs I a/b:Fe "Intro of Course and I:i"
.na pro Professor Professor
.ad
(Professor ENTERS AND GOES TO LECTERN.)
.ch pro
Good evening, class. 
This course is FASSical Studies, or as some of my students last year
called it: Hunks o' History.
.ex
You all have the course outline in front of you (HOLDS UP
PROGRAM). If you turn to page 3 you will see that 40% of
the course will be studied before the midterm and 30%
afterwards. There is no final, and bribing the professor
is encouraged.
.ex
Call me old fashioned but I ask that you do not bring
food or drinks to lectures as I find them distracting.
The same can be said for cigarettes. Cameras and tape
recorders are also forbidden, as the course is available
from Correspondence already and I don't want to cut down
on my royalty income.
.ex
This course is an examination of the creation and evolu-
tion of the University of Waterloo and its parallels with
the evolution of western civilization, if the term
civilization can be given to a society that includes
engineering.
.ex
I will be making extensive use of audio-visual aids in
teaching this course. I may also take advantage of the
wide variety of experts on faculty by bringing in guest
lecturers.
.ex
As time is short, let's get started right away, shall we?
.ex
What is it that separates man from the rest of the animal
kingdom?  There are many answers to that question. Some
say it is man's interest in the arts. I believe it is
man's intellect. Intelligence is one of the paradoxes of
our evolution. Knowledge threw us out of the Garden of
Eden, yet knowledge is what lets us enter a university.
In this first lecture I will show how man developed
language and, as a result, became the grand creature he
was destined to be!
.ad
(EXIT Professor)
.es
.bs I c:Fe "Intro of I:ii - Terry Qualter"
.na pro Professor Professor
.na qual Terry~Qualter Qualter
.ch pro
I would now like to introduce Professor Qualter of the Political
Science Dpartment.  Professor Qualter was one of the original
lecturers for FASS in 1963.  Sir?
.ch qual
Thank you.
Having discovered language, man's next invention was a fairly obvious one:
politics.  As soon as men started talking to one another the fighting broke
out.  
In their early years universities were violent and self-serving places.
"Every man for
himself" was the prevalent attitude.  People thought nothing of stabbing
colleagues in the back and taking credit for their work.
It's nothing like that now, of course.
One of the Great Wars was fought between Troy and Athens.
Actually, it wasn't, but the script demands
historical distortion to introduce the next scene.
The war between Waterloo and Wilfrid Laurier.
.es
.bs I d:Fe "Intro of I:iii - Phil Eastman"
.na pro Professor Professor
.na st1 Student~1 Student~1
.na st2 Student~2 Student~2
.na sci Phil~Eastman Eastman
.ch pro
The Dark Ages were characterised by great ignorance and nothing very
important happening.
.ad
(CURTAIN OPENS ON A DARK STAGE)
.ch st1
How many students does it take to change a light bulb?
.ch st2
A what?
.ad
(CURTAIN CLOSES)
.ch pro
For the next lecture I would like to introduce Dr. Phil Eastman
from the Physics Department.
Dr. Eastman is a longtime supporter of FASSical Studies and
we are honoured by his presence tonight.
.ch sci
Arthur C. Clarke, an author of several science type books,
once said, "any sufficiently advanced science is indistinguishable
from magic."
I guess this is why I was asked to give the lecture on
Merlin, King Arthur and the Round Table.
I approached this task with trepidation until I realized
that the corollary of that statement is also true.
In those days, science was simply sufficiently advanced magic.
While much had been lost in the Dark Ages
(misplaced in the dark, I suppose)
it was all being rediscovered.
It must have been an exciting time.
Universities were gaining more stucture as an academic
hierarchy developed to parallel the nobility:
deans and professors on top, under-graduates on the bottom
or to put it another way,
under-graduates under graduates.
Here, now, a typical day in the Faculty of Science, sorry, Magic.
.es
.bs I e:Fe "Intro of I:iv - Rota Lister"
.na pro Professor Professor
.na list Rota~Lister Lister
.ch pro
We now reach the Renaissance, the time of Guttenberg,
the time of Shakespeare.
My next guest lecturer who is discribed as 'unique'
and 'an individual' in the department of English:
Dr. Rota Lister.
.ch list
Yes, of course, tonight we improvise.
My old teacher at the University of Toronto,
the late Canadian guru Marshall McLuhan,
breathed hot and cool about Guttenberg and his press,
his Galaxy.
What a star-tossed venture!
When I was a graduate student in his seminar at the Centre
for Culture and Communication,
I knew what an enviroment was!
And an anti-enviroment!
But now it's not nearly so clear any more.
Was the medium really a message,
or was it just inter-galactic graffiti done by a Renaissance
buccaneers?
Did Guttenberg reallly invent movable type or was he just
a front for a Machiavellian plot to dislocate the monarchies
of the time, to get all those dumb plebeians to run for
elected office?
.ex
But Mac, of course, knew that the real media revolution
was an electronic one, that Marconi and Wiener and all the rest
gave us all such a bums' rush that nowadays even a University
campus has to have at least two hot/cool tabloids to keep us
from losing touch with the Global Village.
So here we are, witnesses to the MacLunacy of the
Gazette and Imprint, as we observe the commotion
in the Imprint office before they put the paper to bed
for their Friday deadline.
.es
.bs I f:Fe "Intro of Intermission"
.na pro Professor Professor
.ch pro
All right, as we are having a double lecture
tonight I think this is an appropriate time for a break.
We'll be starting again in 10 minutes. Please be prompt
in returning.
.es
.bs II a:Fe "Intro to II:i - John Capindale"
.na pro Professor Professor
.na capin John~Capindale Capindale
.ch pro
Now, if we're all QUITE ready?
My next guest is Professor John Capindale who praticipated
in the first offering of FASSical Studies in 1963.
.ch capin
Good evening.
Some of you know that I am from the Faculty of Science.
When I was approached about taking part in FASS this year,
I asked if the scene I was introducing had anything to do
with my field: chemistry.  
I was told, and I quote, "well, yes, it's bio-chemistry".
I guess it depends on your definition of bio-chemisrty.
This scene deals with student life, you know, the
boy meets girl type of biochemistry.
As my student days happened over... ten... years ago
I don't feel I have much to add to the discussion.
So, here now, the Campus Centre as it was in the late 1700's.
.es
.bs II b:Fe "Intro of II:ii - Larry Smith"
.na pro Professor Professor
.na smit Larry~Smith Smith
.ch pro
If I asked you to name a professor from a department other than you
your own, most of you would probably say Larry Smith.
Those of you who didn't would be from his department: economics.
Tonight we age lucky enought to have him with us.
Professor Smith...
.ch smit
We've heard a lot about politics and science and other
things tonight, but 
we have ignored the paramount discipline
of the University.  Mine.  Economics.
Without which human existance is not possible.
Without which you are merely debris on the ocean of life.
So, we need a lesson in economics.
In the 1920's Prohibition was declared.
As we all know, when something is banned there is automatically a source of
income in suppling that thing illicitly.
The basic law of supply and demand.
Organised crime set up speakeasies
to quench the thirst of the public. 
The universities did not escape the
gangland violence that soon followed.
At Waterloo the speakeaywas in an old
farmhouse on a hill and the gang was called the Mathia.
.es
.bs II c:Fe "Intro of II:iii"
.na pro Professor Professor
.na stu1 Student~1 Student~1
.na stu2 Student~2 Student~2
.ch pro
We now come to the present day which, in my
humble opinion is characterised by great ignorance and
nothing very important happening.
.ad
(CURTAIN OPENS ON A DARK STAGE)
.ch stu1
How much power does it take to change a light
bulb?
.ch stu2
A Watt!
.ad
(CURTAIN CLOSES)
.ch pro
For this last lecture I would like to look at
the future of universities in general and the University
of Waterloo in particular. We've all seen the trends:
funding cutbacks, a more conservative student body,
rising stereo prices. How will the universities of today
prepare for tomorrow? Here for you now is a speculative
look at a possible future.
.es
