#: FASS 1981 Script: FASSified Information
#Title: FASS 1981: FASSified Information
# This play was written and performed by the FASS (Faculty, Administration, Staff & Students) Theatre Company
# of the University of Waterloo in 1981. FASS is an all-amateur theatre company, founded in 1961, which produces
# a campus satirical review every February. The entire production is written and performed by amateur volunteers,
# drawn from the University of Waterloo community. Participation is open to all, and everyone who signs up is 
# guaranteed a role.
#
# FASSified information was performed 5 times in February, 1981 in Theatre of the Arts at the University of Waterloo:
#
#    Wednesday, February 4, 1981, at 8pm
#    Thursday,  February 5, 1981, at 8pm
#    Friday,    February 6, 1981, at 7pm and 10pm
#    Saturday,  February 7, 1981, at 8pm
#    
# Original production credits:
#    Director:                     Ian Chaprin
#    Music Co-Directors:           Jim Gardner, Andrew Malton
#    Pianist:                      Andrew Malton
#    Tenor Saxophone:              Guy Middleton
#    C Melody Saxophone:           Neil Kennedy
#    B Flat Trumpet:               Alan Baker
#    Piano and vocal arrangements: Jim Gardner
#    Technical Director:           Joe Supple
#    Stage Manager:                Tom Hocaliuk
#    Assistant Stage Managers:     Karyl Robinson, Mark Christensen
#    Grips:                        Kerstin Muth, James Nicoll, Krisit Robinson,
#                                  Tracy Tims, Craig Acton, Steve Nicoll, Brenda Parsons
#    Lighting Design:              Peter Carette
#    Lighting Booth:               Carol Wood
#    Sound Booth:                  Judy McMullan
#    Sound:                        Brad Templeton, Ian! Allen
#    Special Effects:              Peter (Boom-Boom) Carette
#    Runner:                       Erika Hocaliuk
#    Coordination and Placement (Choreography):
#                                  Betsy Wimbs
#    Property Master:              Richard Kular
#    Master Carpenter:             Ian McLennan
#    Makeup:                       Janet Acton
#    Makeup Assistants:            Juana Bastedo, Linda Carson, Elisabeth Fraser, Preston Gurd, Steve Hull,
#                                  Chris Joselin, Mary Ann Krakar, Holly McDonald, Judy McMullan, Steven Nicoll,
#                                  Samm Ristich, Gillian Teichert, Maggie Varadi, Kay Weber
#    Costumes:                     Linda Carson
#    Costume Assistants:           Janet Acton, Juana Bastedo, Cindy Evans, Lorraine Galvin, Marney Heatley,
#                                  Katherine Hicks, Erika Hocaliuk, Steve Hull, Louise Klein, Mary Ann Krakar,
#                                  Anna Lebo, Brian Martin, Holly McDonald, Judy McMullan, Judy Morellato
#                                  Kristin uth, Lise Permezel, Karen Rooke, Marnie Shaw, Maggie Varadi, Joanne West
#    Sets and Props: Construction, Destruction, Design and Repair:
#                                  Tracey Allen, Peter Bain, Alan Bowler, Ray Butterworth, Helen Delton, Cindy Evans,
#                                  Elisabeth Fraser, Peter Fraser, Roy Gilpin, Ruth Hawkins, Gordon Irish, 
#                                  Mary Ann Krakar, Richard Kular, J.J. Long, Ken Lynch, Cameron McDonald,
#                                  Grant Montag, Kerstin Muth, James Nicoll, Scott Nicoll, Brenda Parsons,
#                                  Krisit Robinson, Steve Southcott, Tracy Tims, Kay Weber, Carol Wood
#    Videotape Crew:               Ashok Patel, Gord Irish, Ralph Hill, Rohan Jayasekera
#    Photography:                  Chris Dobbin, Preston Gurd, J.W.B (Bast)
#    Artwork and Graphics:         Earl Stieler, Elisabeth Fraser, Andrew Zador, Maggie Varadi, Scott Nicoll, Ian! Allen
#    Special Thanks from the Tech Crew to:
#                                  Earl Stieler, Peter Carette, Alex Kordics, Ken Lynch, Scott Nicoll, Peter Fraser
#    Scriptwriters:                Janet Acton, Robert Bell, Roberta carter, Ian Chaprin, Ron Dragushan, Jim Gardner,
#                                  Jeph Hayes, Dave Haynes, Marney Heatley, Steve Hutton, Ken Lynch, J.D. Nicoll,
#                                  Bernie Roehl, Dave Spence, Joe Supple, Brad Templeton
#    Scriptwriting Assistance By:  Ian! Allen, Linda Carson, Roy Gilpin, William Hughes, Steve Hull, Neil Kennedy,
#                                  J.J. Long, Louise Love, Gillian Teichert, Maggie Varadi
#    Producer:                     Bernie Roehl
#
# The 1981 FASS Committee:
#    President:                    Chris Dobbin
#    Vice-President:               Peter Carette
#    Secretary:                    Maggie Varadi
#    Treasurer:                    Tom Hocaliuk
#    Director:                     Ian Chaprin
#    Producer:                     Bernie Roehl
#    Head Scriptwriter:            Dave Spence
#    Technical Director:           Joe Supple
#    Faculty Rep:                  Phil Eastman
#    Administration Rep:           Peter Fraser
#    Staff Rep:                    Alex Kordics
#    Student Rep:                  Claudette Gagnon
#    Past President:               Preston Gurd
#    Past Director:                Jim Gardner
#    Past Producer:                Ron Dragushan
#    Past Scriptwriter:            Ian! Allen
#    Past Technical Directors:     Scott Nicoll, John Primeau
#    Honorary Member:              Doug Crichton
#
# Song List: #: TODO Get songwriting credits
#   Song:                                 To the Tune Of:
#   This is the FASS Show (Opening Song)  Yankee Doodle Dandy
#   A Bit Of Oil                          Wouldn't It Be Lovely
#   Rhinestone Robot                      Rhinestone Cowboy
#   The Bright Side Of Life               The Obvious Song
#   Amputation                            Toucha-Toucha
#   Mister Screw                          Mr. Kite
#   War Games                             Sister Golden Hair                 #: TODO Not listed in program, was it cut?
#   Lasers And Phasers                    Favorite Things
#   The Canadian National Unity Song      Hallelujah Chorus
#   Fassablanca Anthem                    Carling's Red Cap
#   Happy Elves                           Jingle Bells
#   B.L.C.R.A.                            Supercalifragilisticexpialidocious
#   A Spoonful of Slander                 A Spoonful of Sugar
#   Smear Them                            Both Sides Now
#   Down With The Army                    Balls To Your Partner
#   Santa Wants a Corner (Closing Song)   Obladi Oblada
#
# Additional photos and other information are available at
#
#    Photos  https://plus.google.com/u/0/photos/103202787649310540802/albums/5424268703373360993
#    Program http://www.templetons.com/brad/fass/programs-pdf/81-program.pdf
#
# This script has been recreated from an archival copy of the script provided by Marnie Heatley, with credits and casting
# information from a scanned program provided by Brad Templeton. It was transcribed by Richard LeBer, in February 2012.
#
# As much as possible, the script has been transcribed as performed. Annotations are included where the "as performed"
# script appears to differ from the "as written", based on manual notes and scribbles. Annotations are also provided for
# other information which was interesting (at least to the transcriber). Depending on how this script is formatted and
# printed, formatting, line numbers, etc. may differ from the original script.
#
# All rights retained by the FASS Theatre Company, University of Waterloo

#CAST:
#  Al:        Al Lert,            male,   played by Andrew Zador
#  Alec:      Alec Trolysis,      male,   played by Brad Templeton
#  Anna:      Anna Stesia,        female, played by Valerie Carr
#  Boring:    I.M. Boring,        male,   played by Preston Gurd
#  Charlotte: Charlotte Town,     female, played by Sandy Kemsley
#  Chris:     Chrys Anthemum,     female, played by Marney Heatley    #: Character is named "Chris Anthemum" in the script
#  Co-op:     Co-op Bullet Catchers,      played by Richard LeBer, Peter Scheffel, David Welbourn
#  Dinah:     Dinah Might,        female, played by Heather Lennox
#  Ed:        Ed Monton,          male,   played by David Kerr
#  Fred:      Fred Ricton,        female, played by Gillian Teichert
#  Hal:       Hal Ifax,           female, played by Katherine Hicks
#  Hy:        Hy Pertension,      female, played by Sandy Kemsley
#  Ima:       Ima Undercover,     female, played by Linda Carson
#  Jenny:     Jenny Side,         female, played by Marianne Maltby
#  John:      John Saint's,       male,   played by Roy Gilpin
#  Kay:       Kay Beck,           female, played by Betsy Wimbs
#  Kaz:       Kaz Pajamas,        male,   played by Steve Maulsby
#  Les:       Les Dewitt,         male,   played by Bernie Roehl
#  Manuel:    Manuel Life,        male,   played by Brian Martin
#  Maude:     Maude Squade,       female, played by Joy A. Felton
#  Patty:     Patty Cake                                              #: TODO Character name may have changed; it's not in the program
#  Paula:     Paula C. Holder,    female, played by Gillian Teichert
#  Polly:     Polly Sacharide,    female, played by Anna Lebo
#  Phil:      Phil T. Rich,       male,   played by Andrew Forber
#  Pierce:    Pierce Dearz                                            #: TODO Character name may have changed; it's not in the program
#  Queen:     Queen Spark,        male,   played by Brian Martin
#  Reg:       Reg Ina,            male,   played by Peter Scheffel
#  Ringo:     Ringo Roundacollar, male,   played by John Ciessen      #: TODO "Ciessen" may be wrong -- it's illegible in the program
#  Seymour:   Seymour Clearly,    male,   played by Andre Cyr
#  Sven:      Sven Yearitch,      male,   played by Ian! Allen
#  Tess:      Tess Tube,          female, played by Samm Ristich
#  Trix:      Trix R. Forkids                                         #: TODO Character name may have changed; it's not in the program
#  Vic:       Vic Toria,          male,   played by Derek Wilkinson
#  Winnie:    Winnie Peg                                              #: TODO Character name may have changed; it's not in the program
#  XRay:      Dr. X-Ray Tube,     female, played by Linda Ryall       #: Character is named "X Ray Tube" in the script
#  Yves:      Yves Dropping,      male,   played by Glenn St. Germain

  SONG: Opening Song
  (To the tune of Yankee Doodle Dandy)
  This is the one and only FASS show,
  It's sure to make you laugh or cry
  Don't waste your time on any drugs or booze
  We're bound to give you a high
  We've got talent yet still hidden
  We want to show it all to you
  
  Take your seats and clap your hands
  Get in with the rhythm
  We want to share it all with you
  
  We've got actors, singers, dancers,
  They'll make your senses start to spin
  A story written just with you in mind
  Based [revision: on => upon] sex, crime, and sin.
  Full of puns and silly satire
  Sure to make you lose your mind
  
  Got your money, too late now
  You will have to suffer
  Na Na, Na, Na, Na, Na, Na, Na.
  
  Here's the lovely FASS sweethearts
  And the studs that make them sigh
  We've worked all year to perfect this show
  [revision: And trying => Trying] to make this verse rhyme
  Our costumes [revision: have been completed => now are finished]
  The props are in their [revision: => proper] place
  
  Love our techies, love them all
  They work so hard to make it
  When you get them into bed
  All they do is fake it.
  
  Let's go on now with the show
  Hope that it will seize you
  Hope that it will entertain
  We want for it to please you...
  
Scene 1 - 2 : Insurance Agents and Secret Agents

<LIGHTS>
<Scene opens with a long table with charis and no people on stage. Enter Pierce Dears; He
sneaks on stage and sits down. Ima Undercover does the same. Rest of spices enter in ones and twos.>

[revision: Pierce => Dinah]: <Hushed> The cock crows at midnight.

Ima: The wicked witch is dead.

Ringo: The King's horses have the trots.

Sven: My hovercraft is full of eels.

Maude: The Alcan Can-Can Tin-Cans can Can-can...

Chris: Is there anyone here who's NOT a spy?

<Everybody looks around -- no response>

Chris: Let's cut the cutesie-poo dialogue and start speaking English.

Yves: Maudit Anglais!

[revision: Trix => Kaz]: I don't see what's wrong with spy-talk. Back in the the old days, we always spoke in code.
But this younger generation has no respect for tradition.

[revision: Kaz => Chris]: Yeah, [revision: those were the days => I guess those must have been the days] -- when
spying was a respectable profession.

[revision: Trix => Kaz]: When Ronald Reagan was acting in Bonzo movies.

[revision: Kaz => Chris]: When Bonzo was acting in Ronald Reagan movies.

[revision: Trix => Kaz]: When the Chevron was a newspaper.

[revision: Kaz => Chris]: You're that old???

<Enter I.M. Boring>

Boring: Good afternoon, Ladies and Gentlemen. I am Mr. I.M. Boring and I represent your employer.

Yves: Our employer? Who are we working for?

Boring: Let's just say you're working for five hundred dollars a day plus expenses. Is that satisfactory? <Pause> Good. Of the two thousand spies who applied for this job, only 100 have been chosen.
You have all gone through a thorough selection process designed to find the best spies in the world. Not to mention the cheapest.

Dinah: What selection process?

Ringo: Don't you remember sending in 5 Oh Henry wrappers and two Fruit Loops box tops?

Dinah: I thought I was applying for grad school.

Boring: It is necessary for you to fill out these forms for Income Tax purposes. <He hands out forms.> They're really
quite simple, but please listen carefully to my instructions -- I do not intend to repeat myself.

Chris: What did you say?

Boring: I said, I don't intend to repeat myself! <Pause> Now, in space 1 enter your total income for the year 1980.
Then deduct all amounts investin in an RRSP, RHOSP or RSVP. Put the result in box 2. Take the result out of Box 2.
Multimply this value by the taxation factor found in Table 27B. Deduct from this amount the wind-speed velocity of a laden tree swallow.
Take the square root of this number and enter it in box 27. Plot it as a function of your contributions to WATFUND in the next five years (on average, with standard deviation not to exceed 50%).
Set the derivative equal to zero and solve for x.
This is multiplied by the Superfluous Multiplier Factor found in table 31C.
Exchange with your neighbour and sign on the dotted line. Any questions?

<All the actors hold up hands.>

Boring: Good. Now there are some Life Insurance people who would like to talk to you.

<Enter Manuel and Paula.>

Boring: This is Manuel Life and this is Paula C. Holder. Carry on, you two.

Manuel: Hi there, friends. Have you ever considered what would happen to your loved ones if, heaven forbid, you were transferred to that great multi-national in the sky?

Paula: Think of your children begging for OSAP grants in the streets... your mother forced to do auto repairs to survive...

Manuel: Why not provide for your loved ones in advance by buying a policy from the Expendable Life Insurance Company?

Paula: Yes, at Expendable Life we offer complete coverage. You get both life and injury insurance
for a mere $5000 a year, payable annually or in convenient daily installments.

Manuel: You'll sleep easily in the knowledge that your family's fully cared for.

Kaz: Just what coverage would I get?

  SONG: Amputation
  (To the tune of Toucha-Toucha, from the Rocky Horror Picture Show)
  Manuel, Paula:
  If your pinkie's cut off... don't scoff
  You'll get a dollar forty-nine...
  (You mean me? Uh-huh.)
  Your policy will insure any part you injure
  Be it ankle, elbow, or middle fin-ger
  
  So if you lose a toe, let us know
  We'll pay you seven eighty-four
  And that's just one small fraction
  of your monetary satisfaction
  You get a thousand bucks if you're put in traction
  
  Ampu-ampu-amputation
  Of any part of your anatomy
  Just name it, maim it, then claim it
  You'll be reimbursed
  
  If you happen to die no need to cry
  We'll handle every last detail
  If you need a grave we'll dig one
  If you need a wake we'll rig one
  We pay for everything when you bite the big one
  
  ....CHORUS....
  
Paula: <Passing out forms to spies> Now, if you'll just sign on the dotted line...

<The spies sign the policies.>

Boring: Thank you. Now if you'll excuse us for a moment we will continue with some other business.

<Manuel and Paula exit. The spies talk amongst themselves for a few moments, then Dr. X. Ray Tube enters,
wearing a white lab coat. He carries a machine gun.>

XRay: Ladies and Gentlemen.

<The spies continue to talk.>

XRay: Ladies and Gentlemen! I have been chosen to give you your briefing. You have a very dangerous
mission ahead of you.

Yves: Are we going to smuggle guns into Afghanistan?

XRay: No, something really dangerous...

Maude: <Horrified> You mean w're going to steal the ridgid tool

XRay: I said dangerous, not suicidal. You're going to steal military secrets from a foreign embassy.

<Oohs and ahhs from the spies.>

XRay: Now to help on your mission, we're going to show you some of the things that you're likely to find in a standard foreign embassy.

<Two grips ring in a desk.>

XRay: Now this is a standard embassy desk. YOu will find desks like this in embassies all over the world.
Note the working telephone and the embassy name, in this case "Embassy A".

<The grips carry on the safe.>

XRay: Note the standard computerized alarm panel beside the door on these safes.

Chris: What alarm panel?

<An arm reaches out and slaps the panel on the door.>

XRay: This panel.

<The grips carry on a sleeping guard.>

XRay: And this is the standard embassy guard. Note the look of keen intellect, the aura of awareness, the savage ferocity lurking just under the surface.

<The guard snores loudly. The rest of the equipment is brought on as XRay continues talking.>

XRay: Now we want you all to sneak into various embassies around the world.

Dinah: How do we get in?

Boring: Through the standard embassy secret door located here behind the guard.

<He opens up the trap.>

Dinah: Looks like a trap to me.

Boring: You will go to the safes and you will steal the most top secret war plans you can find.
You will bring them back here where we will put those plans to our own fiendish uses. Any questions? Good. Then I'll pass you back to our friends from Expendable Life.

<Paula and Manuel re-enter. They see X-Ray and his machine gun.>

Manuel: That man has a gun!

Paula: Stay away from those precious life insured bodies with that gun!

XRay: I think they've seen guns before. They are spies, after all...

Manuel, Paula: SPIES!?!?!?

Manuel: Mr. Boring told us they were accountants...

<The spies laugh.>

Paula: We've been had!!!

XRay: Well, that's all folks. Happy accounting.

<Dr. Tube laughs and exits.>

Manuel: <In disbelief> Mr. Boring lied to us.

Paula: We just insured 100 spies! When head office finds out, we'll be sent to the north pole!

Manuel: Well, Eskimos need life insurance too.

Paula: Don't be such a drip! We're ruined!

Manuel: It doesn't seem fair...

Paula: We've got to come up with some way to keep those spies alive.

Manuel: But how?

Paula: I've got an idea. Yes, it just might work...

Manuel: What is it? What is it?

<Paula whispers in Manuel's ear. He reacts with shock.>

Manuel: That's terrible!

Paula: Do we have any choice?

Manuel: Well, all's fair in love and insurance.

Paula: Insurance makes strange bedfellows.

[revision: Pierce => Dinah]: The cock crows at midnight.

[revision: Ima => Maude]: The Wicked Witch is dead...

<LIGHTS: Lights down.>

Scene 1 - 3: A Tough Safe to Crack

<LIGHTS>
<Scene opens with desk downstage by trap and plants stage left and stage right. There is a guard, Al Lert, sleeping at the desk.
The other guards enter through the safes.>

Patty: Boy, it sure is easy making these rounds ever since we found out about the steam tunnels behind the safes.

Hy: You aren't kidding! Just think, it used to take us almost a whole hour to make one round.

Patty: But now we can do the whole building in 15 minutes.

Jenny: And that means we've got 45 minutes to play cards before the next round. Let's go.

<Guards exit through vom. The trap opens and the spies enter slowly and cautiously. Yves heads back towards the safes as the others gather in front of the desk.>

Chris: OK troops, you know what we're here for.

Yves: We find de plans, copy dem, and leave before de guards arrive.

[revision: 
Trix: <Cupping her hand to her ear> Eh?

=>

]

Chris: <To Trix> Let's get started.

[revision:
Trix: Eh?
=> ]

Chris: <Shouting> Let's go!

[revision: Trix => Kaz]: If you want, but we haven't got the plans yet.

[revision:

Kaz: Have you got your hearing aid turned down again?

Trix: Eh?

Kaz: Here, let me turn it up.

<He plucks the hearing aid out of her ear and fiddle with it.>

Kaz: Uh-oh.

Yves: Qu'est ce que vous faites?

Kaz: I broke the little knob off.

Trix: Let me try it. <She puts it in her ear.>

Kaz: How is it?

Trix: <Reacting vigourously> You turned it on ful blast!! <Reacts to her own shout.> Arrggh! <She holds the earplug out at arm's length.>

Kaz: Sorry about that!

=>
]

Chris: Can we just get on with cracking the safe?

Yves: Eh boss, dese fools, de alarm, dey turned him off.

Chris: Are you sure?

Yves: De alarm, she is off, and the safe he is open. <He opens de safe.>

Chris: <Alarmed> Wait, it might be a trap!

<Chris, Trix, and Kaz dive for cover but nothing happens.>

Yves: Tabernac, I 'ope all our jobs are dis heasy.

<As Yves get the papers from the safe, the others get up and brush themselves off. Trix starts copying the papers on the desk.
Kaz has his legs crossed and obviously has to go. He waves his hand and Chris notices.>

Chris: Yes, what is it?

Kaz: Boss, I gotta go.

Chris: Yeah, yeah, we'll all go just as soon as the job is done.

Kaz: No boss, I gotta GO.

Chris: If you'd stop interrupting me, we'd all get out of here sooner.

Yves: He means he has to go to the 'loo.

Chris: We'll all go for a drink AFTER the job is done.

Yves: Never mind, just keep copying.

<Chris turns to help Trix as Yves turns to Kaz.>

Yves: Look, dere is a jean hout dere in de hall. Just look hout for de guards and de alarms.

Kaz: Oh thank you. Murky buckets. <Exits out vom.>

Yves: Dat's merci beaucoup! Tete de cochon.

[revision:

Trix: <Shouting> Will you people be quiet! <She grabs her ear and whispers> I shouldn't have shouted.

=>

]

Yves: Finished yet?

Chris: Yes: Let's put these back and get out of here. Where's Kaz?

<SOUND: There is the sound of a flush followed by an alarm. Trix yanks out her hearing aid at the sound of the alarm. The spies dive for cover as the guards enter from the
vom with guns drawn. Al stays asleep. They go to the alarm control panel as the alarm ends.>

Jenny: It can't be the safe alarm, it's not turned on.

Patty: Then at least no one's broken in here.

<They put their guns away.>

Hy: It sure sounded as though it came from here.

Patty: The only other alarm on this floor is the one in the washroom.

Jenny: You mean the one that goes off when take too many paper towels?

<Kaz enters with his arms loaded with paper towels, sticking out of his pockets, out his shoes, in his ears, etc.>

Kaz: Are you ready to go now, boss? Ooops!

Hy: I think we've just found our quicker picker-upper.

<Kaz dives for cover as the guards pull out their guns. As the shooting starts, the two insurance agents enter by the trap, leaving it open.>

Paula: Stop! Stop! Don't shoot them pleases, we could lose our jobs.

Manuel: Besides, you might get blood all over your carpet.

Patty: This isn't carpet, it's parquet.

<Optional voice over: Butter.>

Manuel: It would be such a pity to ruin it, whatever it is.

Hy: Are you two trying to get yourselves killed?

Paula: We're just trying to prevent a lot of needless bloodshed and insurance pay-offs.

Jenny: Look, we have to shoot them or we'll get fired.

Manuel: Couldn't you just capture them?

Patty: I don't know; as security guards, we're paid to fire indiscriminately at anything that moves.

Paula: Look, if they surrender, then you won't have to shoot.

Hy: I suppose so...

Paula: Good. All you spies, surrender right now!

Spies: No!

Manuel: Come on, you guys, be fair. You've been caught and you'll be shot unless you give up on the spot.

Spies: Get stuffed.

Patty: I'm afraid we're going to have to shoot them now.

Paula: We have no choice now, Manuel. We have to use... THEM.

Manuel: <Sadly> All right. <He yells offstage> Bring on the co-op bullet catchers!

<Enter the Co-op Bullet Catchers. The guards start to fire but the bullet catchers dive in front of the spies stopping the bullets.>

Hy: What's going on here?

Paula: We hired a bunch of co-op students as bullet catchers.

Manuel. Yes, they're in co-op Latin.

Co-op: <Being shot> Et tu, Brute!

Other Co-ops: <Charging into bullets> Amo, amas, amat, amamus...

Paula: Hey you spies, get your beautiful life-insured bods out of here.

<Manuel and Paula rush spies out. The Co-op Bullet Catchers interpose themselves between the guards and the escaping spies.>

Hy: I think we have a problem.

Coop2: _You've_ got a problem? We have to get a work report out of this.

<The guards chase the Co-ops out, leaving Al still snoring in the middle of the stage.>

<LIGHTS: Lights down.>

Scene 1 - 5: The Name Of The Game Is Money

<LIGHTS: Lights up to a table stage right with athe four scientists ##or maybe three: Polly Saccharide, Alex Trolysis, Tess Tube## in a huddle.
They are sorting through blueprints and files marked Secret. Seymour enters with more files.>

Seymour: Well, here's everything the last group brought in.

Polly: Good. Then there are only three more groups of spies left to report.

Alec: Finally! It's all beginning to pull together. You're doing a good job, team.

<Tess has opened one of the files and looks astonished.>

Tess: Hey boss, come look at this!

<They all do as Phil, Anna, and Les Dewitt enter.>

Phil: Well, Dewitt, your people better have something to report. It's been over a week now and I've been hearing a lot of complaints from Personnel. 
The spies and the insurance agents have been turning in some pretty strange expense accounts.

Les: I'm sure it's not that bad boss. After all, the spies can steal whatever they want. And what does an insurance agent need?

Phil: Read the list, Anna.

Anna: <Reading a list deadpan> Expense accounts: One large pizza with pepperoni, peanut butter, double banana, double anchovies, yogurt, 23
frisbee guns, 2 boxes of ammunition, 36 pairs of boffer glasses, ##Okay, I'll bite -- what are boffer glasses?## 10 Tom Mix secret decoder
rings, and 1389 co-op students, hold the engineers.

Les: Um, well maybe some of those things are a little bizarre, but we hired the best agents and we'll get results.

Phil: I want to see some results right now!

Les: I brought you here so the R&D team could tell you personally what progress they've made.

Anna: What! You let that group of morons work on this? They had absolutely no workable ideas before...

Les: Well, they're a little like engineers -- they'll never come up with anything original, but if someone gives them an idea,
they can follow it through to its logical conclusion.

Phil: My logical conclusion would be to fire the lot of you if this doesn't work.

Les: Well let's get on with it then. Alec!

<Alec comes out of the huddle as though in a daze.>

Alec: Oh hi Les. You should see some of the great stuff we've got already.

Phil: All right, let's hear what you've got.

<The following song is done with the use of visual aids: maps and so forth.>

# This song does not appear in the program. It may have been cut.

  SONG: War Games
  (To the tune of Sister Golden Hair)
  Scientists:
  We began these plans last Sunday,
  Working hard without a rest,
  And we finished them on Monday,
  So we hope that you're impressed,
  We can go into production
  If you give it your okay,
  We can start our world destruction
      schemes today...
      
  And the generals will order
  Massive armies to alert
  Those who don't have secret weapons
  Will be sure to lose their shirt
  Though they'll try to stop us
  They're doomed to failure
  They just can't top us...
  
  We have maps with secret bases
  Marked in red and white and blue
  Routes for submarine races
  Marked on all the oceans too
  We've got bombers filled with big ones
  They are marked in purple ink
  And all radar installations are in pink.
  
  They will fight out on the beaches
  They will fight out in the air
  They will hang on tight like leeches
  Though they may not have a prayer,
  If they find it thrilling
  The cash will flow in
  We'll make a killing...

Phil: What about weapons?

Polly: Well, we've got...

  SONG: Lasers and Phasers
  (To the tune of Favorite Things)
  Polly:
  Lasers and Phasers and nuclear weapons
  Miniature landmines that you'll love to step on
  Fiendish devices that blow you to bits
  These are the things that we think will be hits.
  
  Robots and androids and sneaky torpedos
  Hand grenades, light sabres, aren't they just neat-o?
  Gadgets designed to go off with a bang
  These are the things for which this song is sang
  
  When the bombs burst, and the guns fire
  And we're feeling blue
  We simply remember these devious things
  And then we know what to do!

Phil: Sounds good. Is that it?

Alec: We're just waiting for the last three groups to report. After we incorporate their information, it should take about
a month before the first units can be shipped out.

Phil: Good, good.

Alec: Oh, here comes one of the groups now.

<Ten people enter wearing parkas with provincial tags ## This would be Vic Toria (British Columbia), Ed Monton (Alberta), 
Reg Ina (Saskatchewan), Winnie Peg (Manitoba), Queen Spark (Ontario), Kay Beck (Quebec, of course), Fred Ricton (New Brunswick),
Hal Ifax (Nova Scotia), Charlotte Town (Prince Edward Island), and John Saint's (Newfoundland). I can find no mention of Winnie
in the program -- I wonder if that part was cut? ##>

Phil: Where have you people been?

Vic: We've been stealing state secrets from Canada.

Ed: You'd be amazed what we've learned.

Reg: For example, the country is run by P.E.T. ## This is a reference to Pierre Elliott Trudeau, Prime Minister at the time ##

Winnie: It's a little confusing but we think it's a Commodore PET microcomputer.

Seymour: They use a microbrain to run the country?

Queen: Hard to believe, isn't it?

Kay: Not only that but we couldn't find out who leads the opposition.

Les: What do you mean?

Fred: We were told that the leader of the Official Opposition was Joseph Who. ## A reference to Joe Clark, the previous Prime Minister
and Leader of the Opposition in 1981. When Clark was elected PM, the Toronto Star famously ran the news under the headline "Joe Who?" ##

Hal: And the country is ripping apart at the seams.

Charlotte: Yah. It's constitutionally weak.

John: Even their national anthem has ten different parts.

<The following song may be doe in ten part harmony or East vs. West vs. Centre.>

  SONG: The Canadian National Unity Song
  (To the tune of the Hallelujah Chorus. Lyrics by Steve Hull)
  Provinces:
  Manitoba, Manitoba
  Manitoba, Manitoba, Saskatchewan.
  Nova Scotia, Nova Scotia
  Nova Scotia, Nova Scotia, Newfoundland.
  British Columbia and Alberta!
    (Nova Scotia, Nova Scotia.
     Manitoba, Manitoba.)
  Prince Edward Island and New Brunswick!
    (Manitoba, Manitoba.
     Nova Scotia, Nova Scotia.)
  Que-bec! ## Sung by Kay Beck, ala "Amen!" ##
  Ontari-ari-ari-o. ## Queen Spark busts in, and signs this to the tune of "A Place To Stand", Ontario's anthem for Expo '67 ##

<The various players pile on Ontario ## Queen Spark ## and pound him out as they go off stage.>

Tess: How terribly provincial.

<LIGHTS: Lights down on company people. The spies from scene 3A and 3B enter from opposite sides of the stage. The 3A folks look torn
to shreds; the 3B folks look very cool.>

Polly: You people look terrible! What happened?

Yves: It was pretty rough dere. We got caught in da act and had to shot hour way hout.

Trix: It was a good things those insurance agents showed up when the shooting started, or we'd look like swiss cheese.

Maude: Insurance agents? What were they doing there?

Kaz: It must have been something to do with the extended coverage policies they sold us. Anyway, they brought in some co-op bullet catchers
and pulled us out.

Chris: Bullet Catcher, that reminds me of some of the jobs I got when I was in Co-op Espionage Studies.

Kaz: You were in Espionage Studies? I was in ES2.

Ringo: You were in ES2? I didn't think it was built yet.

Maude: How could you stand being inside that building?

Kaz: I have nothing against ugly red monstrosities.

Dinah: I remember my first job interview. The interview was hidden in a room somewhere in the northern hemisphere. The first one to find it got the job.

Maude: I applied for that job, but didn't get it. The room was in the Psychology Building. They ended up hiring a monkey.

Yves: Dat's standard university hiring policy.

Kaz: And the school terms weren't any better than the jobs.

Pierce: Our graduating class had an interesting assignment from the student government. We where hired to eliminate some fanatical left wing
radicals who were publishing a silly newspaper. It wasn't hard, we just took them to the university cafeteria.

Trix: We never studied Cruel and Unusual Punishment until Grad School.

Pierce: Well we decided it was kind of rotten too, so we took them to Health Services to get their stomachs pumped.
When the operation was finished, the radicals said they would only pay last year's medical fees, so the doctors pumped back 7 1/2%
of what they'd taken out.

Trix: As I said, we never studied Cruel and Unusual Punishment until Grad School.

<LIGHTS: Lights up on Phil and company. Phil comes back to meet the spies.>

Phil: So there you are. Do you have the information we asked you to steal?

Chris: Right here.

Pierce: And here's ours... you don't mind the pizza stains, do you?

Phil: No problem. You people have done a fine job. A great job. Just wait out here and we'll give you everything you deserve.

<LIGHTS: He walks bak to the Fassablanca folks. Lights down on the spies.>

Phil: Okay, who's going to fire the spies? Anna?

Anna: Why me? You're the boss.

Phil: <Condescendingly> Didn't they teach you anything in Management school? The aide always does the dirty work, and the boss always gets the credit.

Anna: Oh, all right.

<LIGHTS: Anna goes to the spies. Lights up on spies, down on company folks.>

Anna: I'd like to thank you for a job well done, but as of this moment you're fired.

Chris: Don't we get a week's notice?

Anna: Not at $500 a day.

Ringo: But some of us gave up promising positions with our governments for this job. What will we do?

Anna: Go home and apply for unemployment insurance, blackmail some government... it doesn't matter to us.

Maude: There aren't going to be any governments to blackmail. With all that stuff we stole, you people are going to take over the world.

Anna: Don't be silly, we have no interest in that.

Dinah: Then why did you want all those plans?

Anna: We're going to use them to make the best darned war game in the world.

Pierce: War game?

Chris: War game!

Spies: War game!

Ringo: What is this place, anyway?

Anna: It's the Fassablanca Toy Company.

<At this point a big, boffo banner saying Fassablanca appears from the light pipe back stage.>

Chris: But all the secret weapons! The lasers and phasers and nuclear...

Anna: Soon to be available in durable plastic, batteries not included and some assembly required.

Kaz: We laid our lives on the line for a toy company.

Anna: Yep, and we appreciate it. So will the little kiddies. But you're still fired.

<She begins to herd them offstage.>

Maude: You haven't heard the last of us, Fassablanca.

Spies: Right!

<LIGHTS: They exit. Lights up on full stage.>

Anna: I did your dirty work for you, boss.

Phil: <Holding a file> Right, now we have everything we need to make a really boffo game. These plans for the Avro Arrow
## A failed high tech fighter project of Avro Aviation in Malton in the 1950s ## will help to add the necessary touch of realism.
Alec, I want you to get started on the manufacture of this one right away.

Alec: At once, sir.

<He and the others begin to assemble the papers.>

Les: Just think of the spinoffs we could get, boss. Toy cruise missiles! Nuclear Barbie! Atomic Ken!

Phil: The Fassablanca Toy Company will make millions. All rise and sing the company anthem.

  SONG: Fassablance
  (To the tune of the Carling's Red Cap jingle)
  All:
  Toys and games and gadgets
  Dolls and teddy bears
  We love Fassablanca
  We own all the shares
  
  Profit is our motto
  Money is our goal
  For a million dollars
  We would sell our soul.
  
  ... Another verse or two ... ## It's not clear that any other verses were actually written ##
  
  Toys and games and gadgets
  Dolls and GI Joe
  We love Fassablanca
  It rakes in the dough.
  
<LIGHTS: Lights down>