I:1	Days of Future FASS	Page 1
Queueing Me Softly
Cast of Characters:
ROD STIRRING  	(ROD)
FLORA POLISH  	(FLORA)
JAY CLOTH  	(JAY)
WALTER WALL CARPET 	 (WALTER)
NOAH VAIL 	 (NOAH)
[L-1] (LIGHTS UP ON A PAIR OF TWISTING STUDENT LINE-UPS.)
FLORA POLISH:	I've been at University for three years now.
and I've never seen such terrible line-ups.
JAY CLOTH:	If you don't like standing in tine at	Waterloo,
why don't you tine up for u of T?
FLORA:	I am lined up for U of T!
WALTER WALL CARPET:	(IN BRITISH ACCENT:) Lined up for U of
T?	Dreadfully sorry. old thing. but	in	point	of	fact
this isn't the line for U of T.	It's the line-up for Ox-
ford.
FLORA:	You mean...
WALTER:	Yes, my good woman.	This isn't	the	right tine-up
at	all.	The show's barely under way and already you've
missed your queue.
(ADMINISTRATOR NOAH VAIL ENTERS.)
NOAH VAIL:	May I have your attention. please.
(THE LINE-UPS SNAP TO ATTENTION.)
We regret to inform you that there are only enough admit- tance	forms available for half of you.	Being university
students, you will be quick to realize that not	everyone
here	will	be	able	to	register today.	However, being
scholarly and academic folk, you will also realize that there is a fair and equitable method of deciding who gets the forms. That solution is, of courser a fight to the
death.	(HE	RAISES	HIS ARM)	After the count of three.
Ready, one, two. three...
[S-1] (AS THE TWO LINES ARE ABOUT TO CHARGE AT	EACH OTHER.
"THE TWILIGHT ZONE" MUSIC STARTS.)
[L-2] (THE LIGHT CHANGES TO BLOOD RED. AND EVERYONE FREEZES. ROD STIRRING, DRESSED IN SUIT AND TIE, WALKS CAREFULLY BETWEEN THE RIVAL LINES.)
I:1	Queueing Me Softly	Page 2
ROD STIRRING:	(A LA ROCKY HORROR) I would Like. if I may,
to take you on a strange journey. This, ladies	and gen-
tlemen, is the FASS-Night Gallery, a place where tonight, time and space will be made meaningless quantities.	I am
the	curator	of	the	FASS-Night	Gallery, Rod Stirring.
This evening, you will be snatched from the	safety and
security of	your comfortable chair, and hurtled forward
in time to an era that few would care	to	imagine, and,
before this, none have ever seen. The time is the fu- ture, the places an educational institution tormented for over a decade by government cutbacks, declining enroll-
ment, and fringe radical journalists. It is a turoulent world of rampant inflation and desperate measures to con- serve energy and money. The students are products of
mass	programming,	an attempt by a decaying educational
system to save dwindling BIU's during	the cutbacks	and
restraints of the nineteen eighties. Let us now then venture forth into this nebulous future and see what lies there for us. There are tales told of unpardonadly sel- fish men, of sly and unscrupulous characters, and of mon- strous things that go bump in the disco.
ES-27	(THE MUSIC	SWELLS ON THAT SENTENCE. A SIGN SAYING
"DRAMATIC FORESHADOWING" COMES OUT FROM BEHIND THE PIANO.)
But then again, we may find that university	life	hasn't
changed	that	much	after all.	(TURNS TO LEAVE:) jh, in
case any of you suffer from time-sickness and have forgotten your Gravol tablets at home, the washrooms are on the Outer Limits of this theatre. And now. Ladies and gentlemen. FASS 1980.
CS-3J (SUDDENLY THE MUSIC STOPS.) CL-3] (NORMAL LIGHTING.)
NOAH:	(DROPS HIS ARM) Go!
CS-4)	(AT WHICH POINT PANDEMONIUM BREAKS LOOSE AS THE TWO
LINE-UPS ATTACK EACH OTHER, WITH ROD IN THE MIDDLE.	OVER
THE P.A.	ARE	SOUNDS OF A HUGE BRAWL:. PUNCHES, GLASS
BREAKING, FURNITURE BREAKING, GUNSHOTS,	SIRENS,	ETC.	THE
FIGHT	DIES QUICKLY.	EVERYONE IS STANDING, LOOKING AROJND,
CONFUSED THAT THE SOUND EFFECT IS	STILL	GOING	FULL-dLAST.
THE FIGHT SOUNDS ARE ABRUPTLY ENDED.)
JAY:	(TO AUDIENCE) I'm sorry, but our director started out
in radio.
ROD:	What are the odds that I get out of this alive?
WALTER:	I'd say. about 25 or 6-to-4.
(MUSIC INTRODUCTION TO "25 OR 6 TO 4", BUT THE SONG ISA)
************************************************************ *****	This is the FASS Show	*****
*****	(to the tune of0	*****
*****	You Are My Sunshine	*****
************************************************************
This is the FASS show, the unsurpassed show. Maybe the last show you'll ever see.
If we're not cautious, you'll all be nauseous. At our scenes of depravity.
So please stay seated, please don't feel cheated. And you'll be treated to some great times.
We alt have terrors of making errors.
As we lose our cues and our tines.
(SUNG WITH 1980 OVERTURE HARMONY)
Some jokes are new, dear, some come from last year. If you think that's weird, what you don't know. We've block the exits, there's lots of sex, it's Time for FASS, so here we go.
[L-4] (MOST PEOPLE EXIT.	LIGHTS REMAIN ON FOR THE NEXT
SCENE.)
- fin -
1:2	Days of Future FASS	Page 1
Science Fiction Double Entendre
Cast of Characters:
SHARON SHARALIKE 	 (SHARON)
LOIS BIDDER   (LOIS) HAILEY PHILLIPS   (HAILEY)
PROFESSOR LANCE LACTIC 	 (LACTIC)
SMEDLEY MERKIN  	(SMEDLEY)
TILDE WINKS	(")
FANNY C. COMETRUE	(FANNY)
BOB N. FRAPPLES  	(603)
KEN U. DIGGIT	(KEN)
AL HANSONDEK 	 (AL)
ANNOUNCER WITH MEGAPHONE  	(ANNOUNCER)
SHIRLEY U.JEST  	(SHIRLEY)
PERRY DOG  	(PERRY)
HARLEY HURTSATALL   (HARLEY) LLEWELYN UFFALONE   (LLEWELYN)
CL-1]	(THE SCENE BEGINS IMMEDIATELY AFTER THE OPENING SONG,
WITHOUT DIMMING THE LIGHTS.	SHARON IS LOOKING AROUND LIKE A
TYPICAL FROSH.)
SHARON SHARALIKE:	First	it	was	refundable society fees,
then refundable Federation fees, and now	I	just	can't
believe it: refundable tuition fees! Gee Lois, it's hard to get used to alt the changes that have happened in the last ten years.
LOIS BIDDER:	I	stiLl	can't	believe you were lost in the
Psychology building all that time, Sharon.	It must	have
been awful.
SHARON:	Ohi	it wasn't	that	bad.	There were plenty of
bananas and cheese and I met this really nice bunch of white rats...
LOIS:	You sure missed some unbelievable changes.	Why just
Last year, they finally managed to automate the univer- sity administration.
SHARON:	Oh, you mean that new computer?
LOIS:	That's	right,	the BURT 9000.	Sometimes, though. I
think att this new automation is getting out of hand.	I
remember	reading in the UW Record that this term they're
going to start bar-coding the frosh.
SHARON:	Yes, I know.
(SHARON TURNS AROUND, REVEALING BAR-CODES ON REAR END.)
LOIS:	And if you think that's strange; last year they tried
to cut costs by putting two elevators in the same snaft.
SHARON:	Really?
LOIS:	Uh-huh.	And what about the correspondence program?
They're starting to phase out all	those	silly	cassette
tapes.	The new plan is to freeze-dry the professor and
send him.	To re-activate, all you do is add hot air.
SHARON:	Everything has improved so much.
LOIS:	Not	everything.	They're	experimenting	with pre-
recorded meals,	too.	The one hitch is that no one can
stand the re-runs.
SHARON:	But Lois, what about all the new programmes?	Just
this	morning	I	ran	into	someone	in	the	Faculty of
Acupuncture.
LOIS:	The Faculty of Acupuncture? Do we have one of those?
SHARON:	Yes, the classes are over in Needles Hall.
(SUDDENLY AN ANNOUNCER HOLDING A MEGAPHONE APPEARS FROM A DOOR MARKED "BOOKSTORE")
ANNOUNCER WITH MEGAPHONE:	Now open for a limited time only.
the University Bookstore!
LOIS:	Quick, Sharon!	Let's get our books.
(LOIS AND SHARON EXIT.	THE	BOOKSTORE	SINGERS	ENTER	IN
DISGUST.)
SHIRLEY U.JEST:	I	don't know what they're in such a hurry
for.
PERRY DOG:	All the book prices just went up another 110 per
cent.
HARLEY HURTSATALL:	And	the	Line-ups	at the cashier move
slower than the continental drift.
LLEWELYN UFFALONE:	Buying books depresses me more every
year.
************************************************************ *****	University Bookstore	*****
*****	(to the tune of:)	*****
*****	Winchester Cathedral	*****
k******k****************************************************
University Bookstore, you're bringing me down. Your prices are high
Your line-ups surround, the building
University Bookstore overcharges and then The University Bookstore
Overcharges again
If a course needs a book Take a look
They know what to do: They handle them all
Large or small
By ordering 27 too few.
The students are shocked by, the money they owes At University Bookstore
You pay through the nose!
(WHILE HOLDING THEIR NOSES:)
Fo-doh-de-doh-doh Fo-doh-de-doh-doh Fo-doh-de-doh-doh De-doh-doh!
(THE SINGERS EXIT.	WE HEAR A LOUD EXPLOSION IN THE TUNNEL,
IMMEDIATELY AFTER WHICH THE TRAP DOOR IS FLUNG OPEN. A LARGE CLOUD OF DENSE SMOKE RISES FROM THE TRAP, FOLLOWED SHORTLY BY SMEDLEY AND HAILE% SMEDLEY HAS CLEARLY HAD THE WORST OF THINGS, AND MAY BE SMOLDERING SLIGHTLY. HAILEY IS WEARING A LAB COAT AND GLASSES LIKE A LIBRARIAN.)
HAILEY PHILLIPS:	Are	you	all right. Smedley?	I'm really
sorry I dragged you into this.
SMEDLEY MERKIN:	Oh, that's all	right.	Halley.	A	tittle
gamma radiation never hurt anybody.
HAILEY:	Still,	don't	you	think	you	should lie down or
something?	I mean, after	all,	there	are	some pretty
volatile chemicals in that lab.	With all the excitement,
who knows what could have happened.
SMEDLEY:	No, Hailey. I'll be okay.	Besides. Professor Lac-
tic will be really mad if we don't get him that report.
(DURING THIS	TIME,	HAILEY HAS BEEN SIPPING FROM A SMALL
BEAKER OF MILK SHE HOLDS IN HER HAND.)
HAILEY:	Report?
SMEDLEY:	Yes, the report on the experiment.
HAILEY:	Experiment?
SMEDLEY:	Yes, the one we were just working on - for Profes-
sor Lactic.
HAILEY:	Professor Lactic?
SMEDLEY:	Yes, Professor Lactic.	Our supervisor.
HAILEY:	Supervisor?
SMEDLEY:	Must	you	repeat everything I say?	You're not a
parrot, are you?
HAILEY:	Parrot?
SMEDLEY:	Hailey, what's wrong with you?	Don't you remember
the project we've been working on for the past year?	The
project to	create	a	biochemical	protein	to maximize
acetylcholine	synthesis in the mammalian cerebral cortex
and medulla oblongata.
HAILEY:	Project?
SMEDLEY:	You know, an enzyme	to	stimulate production of
monosubstituted	biphenol	delta-hydroxyaldehydes	and
ketones to give tetramethytsitane.
HAILEY:	Enzyme?
SMEDLEY:	You know, the study serum.
HAILEY:	Of course, how	could	I	have	forgotten something
like that.	(PAUSE) Do I know you?
SMEDLEY:	Hailey, it's me - Smedley!
HAILEY:	Uh.	right.	Smedley.	That's odd... I seem to be
suffering from mysterious memory lapses.	I	wonder	what
could be causing them?
(SMEDLEY BEGINS SIPPING SOME MILK FROM HAILEY'S GLASS.)
It	couldn't	have been any of the stuff in the Lab. I
mean, you saw what happened.	The only thing Left	intact
was that little beaker.
SMEDLEY:	What little beaker?
HALLEY:	You know,	that	small one - like the one in your
hand.	(PAUSE) Oh dear.
SMEDLEY:	What do you mean. "Oh dear"?
HAILEY:	Smedley, don't you realise that you're	holding the
beaker that everything eventually ended up in?	That must
explain all the memory lapses I've	been	having.	We've
discovered	something that can actually cause a person to
Lose his memory!
SMEDLEY:	We have?
HAILEY:	Of course, it'll be	the	greatest	invention since
Punk Rocks.
SMEDLEY:	Punk Rocks?
HAILEY:	Yeah.	They're a New Wave of Pet Rocks that can't
sing.
SMEDLEY:	Hailey, what are we going to call this anti-memory
stuff?
HAILEY:	Why.	since	I	invented	it. (SHE TAKES A SIP) we
could name it after me.	(PAUSE) What's my name?
SMEDLEY:	It's Hailey Phillips.	We could call it	"Hailey's
Memory Obliterator".
HAILEY:	Hailey's	M.O.? I don't think so.	How about Phil-
lips' Milk of	Amnesia?	(PAUSE)	I	bet	it	keeps	you
Regular.
SMEDLEY:	Yes - you'll forget you're in Co-Op.
HAILEY:	Well,	whatever	we call it, it still works like a
charm.
(SMEDLEY TAKES A SWIG FROM THE GLASS.) SMEDLEY:	What does?
HAILEY:	Oh, never mind.	Smedley	isn't it exciting?	We'll
be famous!
SMEDLEY:	YoLl'ii be famous - ygu discovered it.	(PAUSE) Do
I know you. miss?
HAILEY:	I'm Hailey, Smedley!
SMEDLEY:	Pleased to meet you.	Miss	Smedley.	I've always
wanted to know a world-famous scientist.
HAILEY:	Now.	Smedley,	don't	be modest - you had just as
much to do with it as I did.	Besides...
(SHE TAKES OFF HER GLASSES AND SNUGGLES UP TO SMEDLEY.) without a big,
(SHE LETS DOWN HER HAIR.)
strong man like you I could never have set	up	all	that
heavy equipment.
SMEDLEY:	Oh, it wasn't really anything...
HALLEY:	And working by my side all these months,
(SHE REMOVES HER LAB COAT.)
in	the	Lonely	laboratory...	I don't know what I would
have done without you...
HAILEY:	Then take them off...
(SHE REMOVES HIS GLASSES.	ENTER PROFESSOR LACTIC.)
PROFESSOR LANCE LACTIC:	Well, well, Haitey... I see	you're
hard at work.
HAILEY:	I'll say...
SMEDLEY:	Why,	Professor Lactic.., actually, we've been in
the lab.	Miss Smedley here has discovered...
(THEY SAY THESE TWO LINES TOGETHER:) SMEDLEY:	Halley's M.O.
HAILEY:	Phillips' Milk of Amnesia.
(THEY SWITCH. AND SAY THE LINES TOGETHER AGAIN:)
SMEDLEY:	Phillips' Milk of Amnesia.
HAILEY:	Hailey's M.O.
LACTIC:	I don't care what it's called.., what does it do?
(SMEDLEY TAKES A SWIG.)
SMEDLEY:	What does what do?
(HAILEY TAKES THE GLASS AWAY FROM SMEDLEY AS HE FINISHES THE LAST FEW DREGS.)
HAILEY:	Well,	apparently anyone	who drinks	the stuff
suffers from amnesia.
LACTIC:	Hmmm... Memory lapses, you say?
HAILEY:	No. I said amnesia.
LACTIC:	Oh.	I	forgot.	Well,	you'd	better	be careful
drinking	that stuff, you might forget your whole univer—
sity education, and then you'd have	to enroll	and pay
your	fees	all over again.	(REALIZATION DAWNS:) I think
you two should continue your research... immediately.
SMEDLEY:	Well, we can't.	You sees the lab was... well...
HAILEY:	He means that there was this freak accident.
LACTIC:	A freak accident?	Don't tell me you graduated?
SMEDLEY:	No. no.	See, we were working in the lab	late one
night...
LACTIC:	Smedley, stop singing.
SMEDLEY:	Surely.
HAILEY:	Smedley and I were in the lab when suddenly a Dolt
of lightning lanced out of a clear blue sky and knocked a shelf of chemicals all over the room.
LACTIC:	You	know,	that once	happened to a colleague of
mine.	He said it gave him	strange	and	unusual	super-
powers.
SMEDLEY:	Realty?	Like super-speed or X-ray vision?
LACTIC:	Well. I never found out.	He just spread his wings
and flew away without telling me.
SMEDLEY: Wow!	Maybe I've got super-powers too.	I could oe
just like one of those comic-book heroes!
LACTIC:	With	your	luck,	it would be Casper the Friendly
Ghost.	Now, about this accident; you say	the	chemicals
spilled together and created this Milk of Amnesia?
(POINTS TO THE GLASS IN HAILEY'S HAND.).
SMEDLEY:	No, they spilled on the radio-active spider.
LACTIC:	What radio-active spider?
HAILEY:	The	one	that was raised to manhood by a tribe of
Great African Apes when its parents were kilted by giant bees.
LACTIC:	How did it get to be radio-active?
SMEDLEY:	We bombarded it with gamma rays.
LACTIC:	Obviously.	I suppose the radio-active spider	it
you?
HAILEY:	No, it bit the bionic arm we were working on.
LACTIC:	Do keep going. I can't wait to hear	what happened
next.
SMEDLEY:	Well,	the	bionic arm fell into our vat of super
soldier serum which splashed all over the	brick	of	red
kryptonite	on top of the green Lantern which fell into
the path of our cosmic ray generators thereby	activating
the	batmobite	which	completely	destroyed our lab and
subsequently self-destructed in a burst	of	mystic	sor-
cerous energies.
LACTIC:	Uh-huh.	And then what?
SMEDLEY:	What do you think?	I had to clean the whole mess
up.
LACTIC:	Look, you replicate this amnesia	experiment.	I'm
going straight to the president with this!
(PROFESSOR LACTIC EXITS ABRUPTLY.)
HAILEY:	Strange sort of man, isn't he?	I wonder what makes
him tick?
SMEDLEY:	Yes... "tick", and chime on the quarter hour...
(HAILEY AND SMEDLEY EXIT, JUST AS LOIS AND SHARON RETURN.) SHARON:	Lois, didn't the bookstore used to be a tot bigger?
LOIS:	Yes, but now they only keep one copy of each book.
SHARON:	What do they use all the extra space for?
LOIS:	Xerox machines.
(JUST THEN. BRAD TEMPLETON ENTERS AND DOES A MELODRAMATIC MOANING, GROANING, COLLAPSING SEQUENCE. HE IS FOLLOWED BY TILDE WINKS AND THE FOOD SINGERS.)
LOIS:	What's the matter with him?
TILDE WINKS:	Breakfast at Food Services.
SHARON:	Was it realty that bad?
":	Bad?	Most of it was still molting.	He was lucky his got
away.
LOIS:	tit doesn't seem to think so...
(THE MOANING-GROANING PERSON, FORK STILL IN HAND, SINGS THE FOLLOWING BACKED UP BY THE OTHER SINGERS, WHO SUPPORT HIM UNDER EACH ARM.)
************************************************************ *****	Hey, Food	*****
*****	(to the tune of:)	*****
*****	Hey. Jude	*****
*****************************k******************************
Hey, Food.., don't crawl away... Why don't you stay
A tittle longer?
Starvation is realty making me ill Eating this swill
Make me feel better.
CHORUS:
Better, better, better, better...
************************************************************
*****	Food	Services'	Food	*****
*****	(to	the	tune	of:)	*****
*****	Food.	Glorious	Food	*****

************************************************************
Food. Glorious Food
There's nothing can beat it Food Services food
Nobody can eat it
Murder burgers and onion rings (Edible if you're lucky)
Deep-fried Colonel's budgie wings From Ken-tucky
Food glorious food Bacterial cultures Food Services food Fit eating for vultures.
Rice pudding and mystery meat Brown beans from the Navy
Stale cornflakes and graham wheat What's in the Gravy?
************************************************************ *****	In The Gravy	*****
*****	(to the tune of:)	*****
*****	In The Navy	*****
************************************************************
In	the	Gravy,	you	can	see	things	swim	around
In	the	Gravy,	germs	and	viruses	abound
In	the	Gravy	come	and	see	just	what	we've	caught
In	the	Gravy	in	the	Gravy
They've got stew, they've got stew They've got stew down at Village Two
They've got stews they've got stew They've got stew down at Village Two
************************************************************
*****	South Campus Hall	*****
*****	(to the tune of:)	*****
*****	YMCA	**kir*
************************************************************
South Campus Halt, it's fun to eat at the South Campus Hall...
(THE	SINGERS	EXIT.	:ARCHING AND	SINGING. ALONG wITH THE
MOANER-GROANER.)
SHARON:	Who were they?
	The Village Two People.
(TILDE	EXITS.	WATLEY AND SMEDLEY RETURN.	SMEDLEY AND LOIS
IMMEDIATELY FALL IN LOVE.	HAILEY, STANDING BEHIND	SMEDLEY,
TRIES TO GET HIS ATTENTION; SHARON DOES THE SAME WITH LOIS:)
HAILEY:	Smedley?
SHARON:	Lois?
(LOIS	AND	SMEDLEY NOW	KNOW EACH OTHERS' NAMES, AND POINT
WITH RECOGNITION.)
LOIS:	Smedley?
SMEDLEY:	Lois?
LOIS:	(WITH SCHMALTZ:) Smedley.
SMEDLEY:	(WITH SCHMALTZ:) Lois.
CS-1] (WE HEAR THE	FAMOUS LOVE THEME FROM TCHAIKOVSKY'S
ROMEO AND JULIET. SMEDLEY AND LOIS ENCOUNTER EACH OTHER AND DANCE OUT, LEAVING HAILEY AND SHARON TO LEAVE IN HUFFS. A GROUP OF STUDENTS COMES OUT OF THE BOOKSTORE. FANNY IS WEARING A FOOTBALL SWEATER WHICH SAYS "BUCKETS".)
FANNY C. COMETRUE:	I'm practically broke.	I didn't	expect
all	my books	to cost	that much!	I remember when you
could get a photocopy for just ten cents.
BOB N. FRAPPLES:	Yes, how dimes have	changed.	Well.	I'm
not worried... I'm well off.	And I owe everything I have
to one man.
AL HANSONDEK:	Who, your father?
BOB: No, my bank manager.
KEN U. DIGGIT:	And the clerks are getting really sarcastic.
too.	I needed some typing paper, so I asked one of them
if she kept stationery around the office. She said "No. I try to move around as much as possible."
AL:	Sounds	like my date last night.	I promised to get her
home before 12, but she had 15 and passed out.
FANNY:	Speaking of passing, how did you do on	that English
Language Proficiency exam?
KEN:	Welt, I was close to the right answers.	I figure they
were only about two seats away.
FANNY:	I done real	good.	Anyway.	I'm a	tot	better at
sports.
BOB:	Indoor or outdoor?
FANNY:	Generally, "behind closed".
AL: Oh, do you fool around?
FANNY:	That's my business.
AL:	Oh, a professional...
KEN:	You Like jocks I gather?
FANNY:	I like jocks daytagjx gathers.
BOB:	You know, you're not supposed to wear a football
sweater unless you've made the team...
FANNY:	As a matter of fact...
BOB:	Never mind.
KEN:	Sure is strange being back after spending four months
off campus.	I got stationed in Ft.McMurray.
BOB:	That must've been hell.
KEN:	No, I was sent to Hell last term.
AL: What did you do your work report on?
KEN:	Asbestos.	(PAUSE)	What	kind	of co-op job oid YOU
have?
BOB:	This past term, I was an elevator counter-weight.
AL:	How was it?
BOB:	The job had its ups and downs.
FANNY:	I'm in co-op clothing.
AL:	Yes, your sweater looks like	it's	on	its	Last	work
term.
KEN:	And your pants took like they're on their last legs.
FANNY:	No, I was a tailor in Kitchener-Waterloo.
BOB:	Aha!	A tailor of two cities!
FANNY:	Not	a day passed that someone didn't want into my
pants.
AL:	I hear Paul Simon once had a double work term jou as	a
rock and an island...
KEN:	A	roommate of mine once spent a co-op work term as a
patch of grass.
BOB:	What happened?
KEN:	Cutbacks got him; the poor sod was turfed out	of his
job.
AL:	Well,	my	job was	the	worst	of all.	I was a co-op
typewriter.
OTHER THREE CO-OP STUDENTS:	A co-op typewriter???
AL:	Uh huh.
(HE POSITIONS HIMSELF STAGE LEFT, THEN	STARTS	BEATING	HIS
HANDS ON HIS FOREHEAD AS HE RUNS STAGE RIGHT. YELLS "DING!". AND USES HIS HANDS TO RETURN HIMSELF STAGE LEFT TO REPEAT THE PROCESS. SLIGHT PAUSE.)
FANNY:	What was that?
C5-2] (THE SOUND OF A FLYING SAUCER ZOOMING PAST.) KEN:	Slow reflexes in the sound booth.
BOB:	Look, up there!	That strange red glow... What is it?
AL:	Exit lights.
KEN:	No, it's a flying saucer.	Look, it's heading for the
heating plant!
FANNY:	Cimon, let's follow it and see where it lands!
(THEY RUN OFF. LOIS AND SMEDLEY	RETURN,	SO LOST	IN	EACH
OTHER'S GAZE THAT THEY TRIP ON THE ENTRANCE STEPS.)
LOIS:	Oh Smedley. I've never felt like this before.
SMEDLEY:	No,	you haven't. But. I thought you were going
out with that football player.	What was his name?	Bull-
moose Harrison?
LOIS:	I was, for a while.	But every time I turned around,
he was kissing another woman.
SMEDLEY:	What did you do?
LOIS:	I stopped turning around.	And I stopped	seeing him.
(PAUSE)	Tell me. Smedley, do you have any desires, ambi-
tions or dreams?
SMEDLEY:	Well, Lois, I don't know how to answer that...
LOIS:	Okay, let's concentrate on	gsirea then.
SMEDLEY:	Well,	Lois, now that you mention it. I've always
wanted to...	be a	super-hero.	(HE	RUSHES	AWAY	FROM
LOIS.)	You	know,	like	Superman.	or	Spiderman or The
Incredible Hulk.	I used to dream about Wonder Woman. her
Nuclear	Waist	and	her	Atomic Piles.	I know it sounds
silly, but everyone should have a dream.
************************************************************ *****	I Want To Be A Superhero	*****
*****	(to the tune of:)	**k**
*****	Just An Old-Fashioned Love Song	*****
************************************************************
I want to be a superhero.
Flying through the midnight skies A taped crusader fighting crime.
A superman or Peeping Tom with X-ray eyes.
I'll punch out villains and thieves. Crash, wham, barn, slam. kapow
I'll jump right over the moon And shake hands with the cow...
Smed: I'm going to be a superhero
Know that I can be one if I try.
I'm going to be a superhero
Lois: Smedley, dear, just let me ask you why
You want to run around in cape and longjohns
When you know you might catch cold?
You've better things to fill your time
Than proving to the world that you are Brave and dold Don't go way out on a limb
Where you may be attacked
By supervillains and crooks
I want your bod' intact...
Oh please don't be a superhero
Prove to me you're not that kind of guy
With an attention span of zero
Just minutes with me then you have to fly.

I'm
going to be a superhero Know that I can be one
if I try
I'm
going to be a superhero Soar up and bump
my head against the sky.

Oh,
please don't be a supernero What can women do
with guys who fly?
Oh,
please don't be a superhero I don't want a wing
I want a thigh.
A Motive for Amnesia
Cast of Characters:
MS. BIRDIE NUMNUMS 	 (BIRDIE)
CUSTODIAN ELMER GLOCKENSPIEL  	(ELMER)
PRESIDENT SINCLAIR SINCERE 	 (SINCLAIR)
ERNEST EARNEST 	 (ERNEST)
PROFESSOR LANCE LACTIC 	 (LACTIC)
DEAN EUGENE SARDIRTY 	 (EUGENE)
DEAN CONSTANCE INTERRUPTION	(CONSTANCE)
DEAN JERRY ATRIC  	(JERRY)
DEAN PAT ANSWER  	(PAT)
ADMINISTRATOR NOAH VAIL   (NOAH)
CL-13 (SCENE OPENS ON A CONFERENCE ROOM, WITH A LONG TABLE, SIX CHAIRS. AND A SPECIAL CHAIR FOR THE PRESIDENT OF THE UNIVERSITY. PRESENT ARE THE PRESIDENT. SINCLAIR SINCERE, AND HIS CHIEF ADMINISTRATOR, NOAH VAIL.)
PRESIDENT SINCLAIR SINCERE:	I	won't do it. Noah.	I quit.
If you think I'm going to hang around this university for another second, you're crazy.
ADMINISTRATOR NOAH VAIL:	Now. now, Mr. President. the Deans
will be here any moment and we must be ready	for	them.
mustn't we?
SINCLAIR:	No we mustn't.	This place reminds me of a DC-10;
its liable to crash at any moment.	I'm leaving.
NOAH:	But Mr. President, think of what	the university has
done for you over the years. Don't you remember all the honours we have showered upon you. how we made you Bishop of Renison. Baron of the North Campus. and Earl of Scruggs?
SINCLAIR:	Those petty titles mean nothing to me	any more.
I'm leaving you Flatt.
NOAH:	Don't	you	remember how the University gave you the
key to the executive presidential washroom in	your	hour
of need?
SINCLAIR:	Well, my hour's UP.	I'm leaving.
NOAH:	Don't	you remember how we doubled your salary and
gave you your choice between a Mercedes and a Rolls?
SINCLAIR:	Yeah, but there was no gas for the Rolls	and the
horse	that pulls the Mercedes has faulty emissions.	I'm
Lea ving.
NOAH:	Don't you remember how we found you a secretary who
would voluntarily bring you coffee at your desk?
SINCLAIR:	Sure,	but	she	still	won't come across with a
Danish.	I'm leaving.
(NOAH WHIPS OUT SOME PHOTOGRAPHS.)
NOAH:	Don't you remember these pictures I	took	of	you at
the office Christmas party?
SINCLAIR:	(FIRMLY)	I'm staying.	What is this meeting all
about. anyway?
NOAH:	Our new computer, the BURT 9000, has come to the con-
clusion after careful cost-analysis, that we've reached a do-or-die situation continued-existence-wise. We have to decide today whether or not to sell out the University to some multi-national, imperialistic, oligopolistic, rich corporation.
SINCLAIR:	But I thought we sold out years ago.
NOAH:	Actually, we didn't sell out to the establishment so
much as get into bed with it, and now we are going to g0 all the way.
SINCLAIR:	All I can say is, I hope we don't get screwed.
NOAH:	Mr.President.	I have taken the Liberty of placing
small	ad	in	the	papers.	(READS:)	Southern	Ontario
University	with	new	flagpole	and	fleet of tow trucks
wishes to	sell	out	to	multi-national,	imperialistic,
oligopolistic,	rich	corporation.	Phone 885-1211 during
normal business hours.	Sincere inquiries only please; no
weirdos.
SINCLAIR:	Isn't	that	a	bit excessive?	I think that the
BURT 9000 has made some kind of mistake.
NOAH:	Now now, Mr. President, the idea of having the entire
memory	of a former president of the university in a com-
puter may seem absurd to your but Look at	the economics
of	the situation.	Instead of forking out an enormous
salary for a real president, we simply cough up a	measly
few grand	for a good-natured know-nothing, simpleton
figurehead like you.
SINCLAIR:	I am NOT good-natured!
NOAH:	The money we'll save in	the	first	six	months will
more	than	pay for putting all the president's knowledge
on a tiny, inexpensive chip of silicon.
SINCLAIR:	Isn't it amazing what	they	can	do	with micro-
electronics these days?
NOAH:	Actually, we didn't need to use micro-electronics.
NUMNUMS ENTERS.)
MS. BIRDIE NUMNUMS:	Your Honour, the deans of the faculties
are waiting outside, sir.
SINCLAIR:	Very good, Ms. Numnums, send them in.
BIRDIE:	At once, your holiness!
(NUMNUMS MOTIONS THE DEANS ONSTAGE.)
Right this way, gentlemen.
THE DEANS:
************************************************************ *****	Plato's Retreat	*****
*****	(to the tune of:)	*****
*****	Lollipop Guild	*****
************************************************************
We represent,
The Faculty Club The Faculty Club The Faculty Club.
We represent.
The Faculty Club,
And we thought that we'd come in to kiss your
(PREGNANT PAUSE)... hand!
SINCLAIR:	Good afternoon,	gentlemen.	I'm glad you could
make it.	.
DEAN JERRY ATRIC:	Actually, your secretary turned me	down,
haw, haw haw.
(THE OTHER DEANS JOIN IN AND THE HILARITY BECOMES GENERAL. SINCLAIR CUTS OFF THE LAUGHTER WITH A WAVE OF HIS HAND.).
SINCLAIR:	That will be all for now, Ms. Numnums.
BIRDIE:	Of course, mon generale.
(NUMNUMS EXITS. ON THE WAY OUT SHE BOOTS A DEAN IN THE REAR. HE	YELPS AND STRIKES	THE DEAN BESIDE HIM, WHO YELPS AND
STRIKES THE DEAN BESIDE HER, WHO YELPS AND STRIKES THE DEAN BESIDE HIM, AND GENERAL PUSHING AND SHOVING ENSUE ONLY TO BE INTERRUPTED BY:)
NOAH:	(SCREAMS) Knock it off!
SINCLAIR:	(TO HIMSELF) We don't need fuel rationing in this
place, we need martini rationing.	Ahem.	Gentleman, this
is my chief administrator, Mr. Noah Vail.	Noah,	please
brief	the	deans	on	this	vitally	important	matter,
whatever it is.
NOAH:	Of course. Mr. President.	While you Deans have peen
Playing golf or carousing in the Faculty Club, the BJRT 9000 has been analyzing the problems of this university. In shorts gentlemen. the BURT 9000 has concluded that the university is in a real pickle.
DEAN PAT ANSWER:	Pickle?	You can tell by the crunch?
DEAN CONSTANCE INTERRUPTION:	Sounds like a dilly of a mess!
NOAH:	Quit	gherkin around and listen.	The BURT 9003 says
we've got real problems!	None of this penny	ante	stuff
about	declining	enrolment or non-existent educational
standards, but serious stuff like	where our	next	pay-
cheque	is	going to come from.	What we really need is d
tong term plan to bring in the bucks so we can afford	to
give	ourselves	the	raises,	bonuses, and freebie trips
which we so richty deserve.
THE DEANS:	Hear, Hear!
NOAH:	Gentlemen. I have taken the liberty of assigning one
of	my	first-year co-op acounting students to prepare
recommendations.
JERRY:	You hired a co-op student?
NOAH:	(APOLOGETICALLY:) We couLdn't	afford	to get anyone
competent.	(SHOUTS OFFSTAGE:)	Ms.	Numnums, would you
please bring in Mr. Ernest Earnest?
BIRDIE:	(ECHOING:) Right away, right away.
(NUMNUMS ESCORTS EARNEST ONSTAGE, THEN EXITS.)
NOAH:	Ernest's a good lad.	Very obedient	and works hard.
ALL	of my	people work hard because they like me, isn't
that right Ernest?
ERNEST EARNEST:	Yes, sir.
(NOAH SWITCHES CHARACTER INTO MILITARY MODE.)
NOAH:	I can't hear you.
(ERNEST SNAPS TO ATTENTION AND STARTS SHOUTING:)
ERNEST:	Yes, Sir!
NOAH:	I stilt can't hear you.
ERNEST:	YES, SIR!
NOAH:	Louder.
ERNEST:	Y E S. S I R !
NOAH:	(MILDLY) That's better.	What are you. Ernest?
ERNEST:	Slime, Sir!
NOAH:	What kind of slime. Ernest?
ERNEST:	Lowly Co-Op slime, Sir!
NOAH:	I can't hear you.
ERNEST:	LOWLY CO-OP SLIME, SIR!
NOAH:	And what is your purpose in life?
ERNEST:	To grovel. Sir!
NOAH:	To grovel where?
ERNEST:	To grovel at the feet of my employer. sir!
NOAH: And who is your employer? ERNEST:	You, Sir!
NOAH:	I can't hear you.
ERNEST:	YOU, SIR!
NOAH:	I still can't hear you.
ERNEST:	Y 0 U. S I R !
NOAH:	Very good, Ernest. You may kiss my feet.
ERNEST:	Yes. sir. Thank you. sir. Right away. sir.
(ERNEST GROVELS ON THE FLOOR AND KISSES NOAH'S FEET.)
NOAH:	All right. Ernest, that's enough. Report.
ERNEST:	Yes	sir.	Thank you sir.	(GROVEL. SNIVEL. ABASE,
ABASE:) As you can see by this chart,	our	situation	is
rapidly getting worse.
(HE HOLDS UP A CHART WITH A STEEPLY RISING CURVE.)
DEAN EUGENE SARDIRTY:	That chart looks pretty good to me.
ERNEST:	Unfortunately, this is a chart showing the univer-
sity deficit	and	the	ever-increasing	student	faculty
ratio.	Now tbil chart, on the other hand...
(ROTATES CHART NINETY DEGREES, CURVES NOW FALL STEEPLY:)
...	illustrates the trend in revenue and enrollment.	As
you can see, according to the BURT	9000	fiscal	projec-
tions,	we are going to run out of money by next...	(HIS
FINGER TRACES CURVE OFF THE CHART:) ...Monday!
EUGENE:	Didn't we save a bundle in energy costs by running
the air conditioning in the winter and the heating in the summer?
ERNEST:	Yes.	sir.	But we found we had to spend the money
fixing windows broken during the	summer,	and	floors
ruined by people building fires during the winter.
CONSTANCE:	What	about	the scheme to use Mafia hit men to
collect tuition?
ERNEST:	We lost all we gained when we had to pay increased
Health Services costs.
PAT:	Aren't	we going to make a sizeable chunk of cash by
tossing the computers out of the big Red Room and con- verting it into a high-priced Disco?
ERNEST:	That's	truer gentlemen; but	disco sucks.	(PAUSE
FOR CHEERS!) Gentlemen we are faced with only one alter- native.
CONSTANCE:	And what is that?
ERNEST:	Abolish tenure.
THE DEANS:	(TURN ON HIM AND SHOUT:) Abolish tenure?
(DEAN	JERRY PULLS	OUT A GUN AND SHOOTS ERNEST. wHO DIES
GROVELING.	THE OTHER DEANS CONGRATULATE JERRY.)
SINCLAIR:	Spunky tittle twerp, wasn't he?
NOAH:	That's what's	so nice	about	co-op	students.	You
don't have to recycle them.
(ENTER ELMER GLOCKENSPIEL, SCREAMING.)
CUSTODIAN ELMER GLOCKENSPIEL:	Mr,President!	Little Green
Men are hovering over the PRG Heating Plant, and they're planning to take over the whole universe...ity! I barely got away with my life!
SINCLAIR:	Little Green Men?	Gentlemen,	the	place	is all
yours; I'm leaving.
NOAH:	Calm	down. Mr.President.	You're new here.	"Little
Green Men" is just the affectionate term the students use for	the	University	custodians and heating plant staff.
They all wear green uniforms, just like Elmer here. The idea of them taking over anything is patently ridiculoJs; they couldn't even turn down the heat in my office when I asked them to.
ELMER:	But,	you	don't understand!	The Little Green Men,
they landed in a flying saucer...
NOAH:	(CUTTING HIM OFF STERNLY:) Mr.Glockenspiel, we have
very important business to take care of here.	(POINTS TO
EARNEST:)	Why don't you make yourself useful and arrange
to have this pile of trash disposed of?
ELMER:	You'll be sorry. Sir.	Just	you	wait;	the Little
Green Men are going to be Looking a lot greener before this day is through!
(ELMER EXITS.)
SINCLAIR:	Now then. gentlemen.	Do	you have	any further
ideas on how we are going to save our paycheques?
EUGENE:	Sinclair,	can't	we	just take it out on the stu-
dents?
CONSTANCE:	Sure, we can add an extra year to the optometry
program!
JERRY:	Mr.President, Dean Pat Answer and I thought it might
be best to tackle this problem in the modern idiom.
SINCLAIR:	Who are you calling an idiom?
PAT:	The modern	idiom,	Mr.President,	is	television.	We
could	raise money by sponsoring a catchy University Game
Show.	Dean Jerry Atric wilt demonstrate.
JERRY:	(HAMMING IT:) Good afternoon. Ladies	and Gentlemen,
and welcome	to Canada's	favourite	afternoon pastime:
Bowling for Doctorates.
PAT:	(ALSO HAMMING IT:) If you can't bowl,	then	timber up
your fingers with:	Dialing for Diplomas.
JERRY:	Followed by Graduate for a Day. the All-New Grading
Game, and the Sixty-Four-Thousand-Dollar Tuition!
PAT:	And to top it all off, for you University of Guelph
frosh,	there's the agricultural game show: Reach for the
Crop!
EUGENE:	Yes, I'm sure there are plenty of other ways we can
find to exploit the students.
THE DEANS:
************************************************************ *A.***	50 Ways To Screw The Students	*****
*****	(to the tune of:)	*****
*****	50 Ways To Leave Your Lover	*****
************************************************************
Think up some creative tricks
to get them where it hurts
A skillful way to make sure they
will quickly lose their shirts
A little thought should surety help us
to get our unjust desserts
There must be, fifty ways to screw the students.
Just treat them like mud. Jud.
Give them an exam. Sam.
Tow their buggies away. Ray. But make sure they pay. Lower their loans. Joan.
Make'm pay through the nose. Rose.
You can charge by the day. Gay.
But make sure they pay.
(NUMNUMS RE-ENTERS.)
BIRDIE:	Your gloriousnesss there is	a	person outside who
would speak with you.	A Dr. Lance Lactic.
SINCLAIR:	A Doctor whom?
BIRDIE:	No	sir.	Dr.	Whom was Last year's mad scientist.
Prof Lactic is our mad scientist this year.
SINCLAIR:	Well., I guess it's safe enough to see him.
(LACTIC BURSTS IN.)
PROFESSOR LANCE LACTIC:	All right, you clods; I've sent	27
memos to this office and they've all been to no avail.
(ALL LOOK TO NOAH VAIL.)
NOAH:	Don't look at me.	Everything I get is to Noah Vail.
LACTIC:	I'm	mad	as het! and I'm not going to take it any
more!
SINCLAIR:	Right. Ms. Numnums, would you be so kind	as to
bring some downers for Professor Lactic here?
BIRDIE:	Right away, mon seigneur...
LACTIC:	Stay	where	you	are. Numnums.	Look, Sinclair. I
know att. your sleazy tricks and I'm not	going	to	stand
for them any more.	I'm so mad, I could just spit.
HE TRIES TO SPIT SEVERAL TIMES, BUT FAILS.)
BIRDIE:	Dr.Lactic.	I	didn't	think that the "mad" in mad
scientist meant angry. I thought it meant crazy.
LACTIC:	Crazy?	CRAZY?	CRAZY ?!	Well,	a bit.
(EAGERLY:) Listen to me!	I came in here to reveal to you
a secret that wilt save the university.
NOAH:	What's that?
LACTIC:	I can make the students ignorant.
BIRDIE:	Someone beat you to it. Lance.
LACTIC:	That may be, but the students thiok that	they are
smart!	My	new	secret chemical formula will change all
that.
SINCLAIR:	What is it?
LACTIC:	I call it... Milk of Amnesia.	Just one tiny parsec
of	this	stuff	will make a student forget everything he
has ever learned.	Picture it: a typical	student,	going
to	classes	all term, doing alt the assignments	writing
the midterms...
PAT:	That's a typical student?
LACTIC:	Then one day, the week	before	exams	the student
has	a	glass	of	milk	at	the	cafeteria.	This is no
ordinary milk; this is my secret Milk of Amnesia.	In ex-
actly	two minutes, all that expensive knowledge is gone,
wiped out. poof!	No hope of recovery in time for exams.
What is to be done? The university comes to the rescue. In view of the seriousness of the affliction, the student is permitted to retake, and pay for, the courses next term.
CONSTANCE:	Why, that's astounding!
SINCLAIR:	I get the idea.	We make the same student pay for
his education over and over again!
NOAH:	Quite	right. Mr.President.	Of courses we shouldn't
keep a student around too long, otherwise someone	might
smell a rat.
EUGENE:	People are suspicious enough of grad students as it
is.
CONSTANCE:	So after eight or nine	years	we graduate	the
student; mustn't be too greedy. eh?
LACTIC:	But	before	I	can	save the university. I need a
typical human subject to determine the	exact	dosage	of
Milk.
NOAH:	(TO	THE DEANS:) We wouldn't want students to forget
how to sign cheques, now would we?
SINCLAIR:	Where are we going to find a student	dump enough
to act as a guinea pig?
EUGENE:	How about at our new student Disco?
CONSTANCE:	Sure.	The place will be so dark and noisy that
no one will notice if we bop a student on	the	head and
drag him out the back way.
PAT:	Most of them Look like they've just been bopped on the
head anyway.
EUGENE:	And dragged out the back way.
JERRY:	We could keep the student guinea pig over in the PRG
heating plant	with the	Little	Green Men while Lactic
finds out the dosage.	That way, no one	will	trace	the
student to us.
SINCLAIR:	Great	idea.	Lance.	I	hope	you	can	get it
developed before you leave.
LACTIC:	Leave? Where am I going?
SINCLAIR:	Well, we need some money	for	the Deans' raises
next	week, and since you're the last non-tenured faculty
member.	As of tomorrow, you're fired.
(LACTIC REACTS WITH SHOCKED DISBELIEF.)
All right, gentleman	let's disco!
[S-13 (STRIKE UP THE SOUNDS OF "MACHO MAN".	EXIT DISCOING.)
DEANS:	Students.	Gonna grab some students...
CL-2] (LIGHTS OUT.)
- fin -
1:4	Days of Future FASS	Page 1
Close Encounters with Littte Green Men Cast of Characters:
PRG COMPUTER 	 (COMPUTER)
DAVE 2001   (DAVE)
CHARLIE HORSE	(CHARLIE)
BILL E.CLUB'S VOICE	(BILL E.)
WILLIE DEWITT   (WILLIE) JESSIE WILL   (JESSIE) MAY B.KNOTT (MAY)
DENNIGAN U.NEVERNO 	 (DENNIE)
SOPHOCLES  	(SOPHOCLES)
EURIPI DES	(EURIPIDES)
ARISTOPHANES 	 (ARISTOPHANES)
ABSURDITIES	(ABSURDITIES)
MORRIS     (MORRIS)
CL-1]	(OPEN ON A SET WITH COMPUTER CPU DISPLAY BOARD WITH
CONSOLE IN FOREGROUND AND COAL SHOVELLERS IN THE BACKGROUND. SMOKESTACK BASE HAS SIGN: BOUNCE TUBE. DAVE IS ASLEEP AT CONSOLE AND SEVERAL OTHER PRG PERSONS ARE ASLEEP LYING AROUND THE STAGE. THE COAL THAT THE COAL SHOVELLERS ARE SHOVELLING COULD VERY WELL BE RED STYROFOAM BALLS PAINTED BLACK. THE SHOVELLERS CHANT RHYTHMICALLY.)
CO-OP SHOVELLERS:	Coal;	Bah!	Coat; Bah!	Coal Coal, Coal
Coal, Coat! BAH!
************************************************************ *****	NEIL YOUNG EAT YOUR HEARTH OUT	*****
*****	(to the tune of:)	*****
*****	HEART OF GOLD	*****
************************************************************
We want to• think, we want to drink
We want to get out of this stinking hole
This job's a write-off, we want a night off
But still we're filling up this hearth with coal And we're getting old...
WILLIE DEWITT:	(THROWING DOWN SHOVEL) That's it. I'm taking
a break.
JESSIE WILL:	Right, let's all go for a coke.
(THEY ALL THROW DOWN SHOVELS AND HEAD FOR EXIT.)
MAY B.KNOTT: By the way, who wrote the words to our song? DENNIGAN U.NEVERNO:	I think it was Coal Porter.
(THEY LEAVE. THE COMPUTER BEGINS A SOFT WHOOPING SOUND.)
PRG COMPUTER:	(HAL-LIKE VOICE) Dave. Wake up. Dave. Dave?
(SCREAMING) Wake up. Dave!
CS-11	(INCREDIBLY LOUD ALARM.	LIGHTS,	BELLS,	SIRENS.
BUZZERS, ETC. SOUND.	DAVE RACES TO A NEARBY ALARM CLOCK AND
SHUTS IT OFF.	THE SOUND STOPS IMMEDIATELY.)
COMPUTER:	Emergency condition in building	seventeen, level
three. Dave.
(A DIAL ON THE DISPLAY BOARD RACES TOWARDS DISASTER.) DAVE 2001:	Emergency? Ohmigawd!
(DAVE	TRIES	TO HOLD BACK THE NEEDLE OF THE DISASTER METER.
JUST WHEN DAVE APPEARS TO BE WINNING,	THE COMPUTER'S ARM
COMES OUT AND PULLS THE NEEDLE BACK THE OTHER WAY.)
Help! Help!	Help. Cecil. help!	Guys! Wake up!
(ALL PRG MEN EXCEPT FOR ONE (CHARLIE) WAKE UP WITH A START.) This is an emergency!	Help me out!
THE PRG PEOPLE:	Right!	Let's help him out.
(THEY IMMEDIATELY PICK DAVE UP AND RUN WITH HIM OUT THE VOM. HE RUNS BACK ON.)
DAVE:	I'm glad I didn't ask them to	lend	me	a	hand.	My
only	hope	is that one of our mobile operatives might be
in the area.	(INTO RADIO) Hello, building seventeen?
BILL E.CLUB'S VOICE:	(OVER RADIO) Hello?
DAVE:	Hello? Are you there?
BILL E.:	No. I'm here.
DAVE:	Thank heavens!
BILL E.:	Thank you. heavens.
DAVE:	Bill	there's a critical situation at building seven-
teen.	I'm afraid you're the only one who can handle it.
BILL E.:	But. I'm a bit indisposed at the moment. Dave...
DAVE:	No buts. 3111.
BILL E.:	That's the problem. Dave - my butt.
DAVE:	Quiet.	It's all in your hands now.	If those toilet
rolls aren't changed right away, heaven only	knows	how
many people will suffer.
BILL E.:	I wish you'd told me that a tittle sooner. Dave. I
think I already know about the problem.
DAVE:	You just take care of your end there. Bill.
BILL E.:	Yes. I was planning on doing just that.	Dave, one
last	thing.	What if... What if I found that there were
no spare toilet rolls?
DAVE:	Just put a stack of Gazettes in the tan.
BILL E.:	Roger.
DAVE:	My name's Dave. Bill.
BILL E.:	Sorry, Dave. Over and out.
COMPUTER:	Good work, Dave. And now it's time for a commer-
cial,	brought to you by the wonderful folks at Financial
Services to help pay your salary.
(THE COMPUTER'S HAND TAKES A TAPE CASSETTE PLAYER OUT OF THE COMPUTER ITSELF, AND TURNS IT ON. COMPUTER ARM APPEARS, HOLDING JAR.)
Have you been feeling	irritable	and	restless?	Having
trouble getting to sleep. Dave?	Then try new mellow-ADE.
It's 100% coffee-free. Let's you sleep the	entire	shift
and stay calm.
DAVE:	(TURNS OFF MUSIC AND CONFISCATES JAR) Honestly - you
new computers. I don't mind watching your programs, but listening to your commercials is too much!
COMPUTER:	Sorry, Dave.
DAVE:	And another thing;	don't	ever make that kind of
ruckus again, no matter what the emergency.	You never
know when you might wake up... IT.
CHARLIE HORSE:	(WAKING UP AT LAST) Who are you catting It?
DAVE:	Not you. Charlie.
(PERSON	BEHIND	PIANO	HOLDS	UP	SIGN,	"DRAMATIC
FORESHADOWING".)
Legend has it	that	on	this	night	every hundred	and
eighty-seven years,	five months,	and two parsecs, any
sort of ruckus	runs	the	risk	of	reviving	primordial
forces of evil deep within the grounds of this campus.
CHARLIE:	Speaking	of	grounds,	isn't	it	about time for
another coffee break?
DAVE:	(WAVES AS THE CO-OP PEOPLE RE-ENTER.)	Sure, Charlie.
Maybe	we can get together with the Co-Op Heating Techni-
cians for a few hands of cards.
CHARLIE:	A game of chance?
DAVE:	Not	the way we're gonna play.	Stall 'em for a uit
white I fix the deck.
(CHARLIE NODS. GOES OVER TO THE COAL SHOVELLERS.) CHARLIE:	So how do you folks like the job so far?
WILLIE:	The work you've got us doing isn't a bit	like what
the job description said.
CHARLIE:	Is that so?
(ALL CO-OPS PULL OUT THEIR JOB DESCRIPTION SHEETS.)
JESSIE:	Yeah!	Listen	to this:	(READING:) Students will
gain hands-on experience with the day-to-day operation of a large environment control complex.
MAY:	(READING:)	Special	emphasis	will be placed on faei
analysis and transfer...
DENNIE:	(READING:) As well as in-depth observation of ther-
mal degradation of organic matter.
WILLIE:	We aren't doing any of that stuff.
CHARLIE:	Why,	that describes your job perfectly.	(POINTS
TO THE COAL:) Look, what's that?
JESSIE:	Coal.
CHARLIE:	(AS IF THIS EXPLAINED IT:) Fuel analysis. And what
do you use those shovels for?
MAY:	Putting the coal into the furnace.
CHARLIE:	Fuel transfer. And what happens to the coal in the
furnace?
DENNIE:	It burns.
CHARLIE:	A hearth-warming example	of	in-depth observation
of thermal degradation of organic matter.
WILLIE:	That's ridiculous!	I quit!
CHARLIE:	You	can't	quit,	you're fired! (GRABS CO-OP AND
THROWS HER INTO THE FURNACE) And glazed.
JESSIE:	Wow! Look at that flame! How big	is	this furnace.
anyway?
CHARLIE:	Oh. about 14.000 BIU's... I mean BTU's.
CHARLIE NOTICES DAVE SIGNALLING TO KEEP THEM OCCUPIED.)
Say.	I'll	bet	you boys haven't had the grand tour yet.
Wett, why don't I show you around?
(CHARLIE BEGINS WALKING THEM OFF STAGE.)
MAY:	Is it true that the guy in charge	of	this	place has
two horns on his head and a big red tail?
CHARLIE:	flaw,	that's just a rumour started by someone who
tried to get the heat turned down in his office.
(CHARLIE AND THE CO-OP-ERS LEAVE.	THE ALIENS ARRIVE VIA THE
SMOKESTACK:	SOPHOCLES,	EURIPIDES,	ARISTOPHANES	AND
ABSURDITIES.	DAVE IS MIRACULOUSLY OBLIVIOUS TO ALL THAT THE
ALIENS	SAY AND DO, SO ENGROSSED IS HE IN THE TASK OF FIXING
A DECK.)
SOPHOCLES: Gather round me, crew, and	review our plan.
(ALIENS GATHER AROUND THEIR LEADER.)
Although we have been extensivety trained to look,	talk,
and act like humans...
(ABSURDITIES	IS WATCHING SOPHOCLES	INTENTLY,	HIS	MOUTH
HANGING OPEN AND A DUMB EXPRESSION ON HIS FACE.)
... at least, some of us act like humans, we	must	never
forget	that	we	are	atien	invaders	from the glorious
planet - Bonzo Cat!
(THE OTHERS ALL MAKE MEOWING SOUNDS.)
Thank you. Now I'm certain that I don't have to tell	you
that,	as alien invaders from the glorious planet Bonzo
Cat...
(MEOWING SOUNDS AGAIN.)
−	thank you -	it	is	our	mission	to	take	over	the
universe.	And. I'm sure there is no need to tell you, as
alien invaders from the glorious planet Bonzo Cat...
(MEOWS.)
−	thank you - whose	mission	it	is	to	take over	the
universe,	we have	been sent	to	the nefarious planet
Mother Earth...
(ABSURDITIES MEOWS. THE OTHERS GLARE AT HIM.) ABSURDITIES:	Sorry.
SOPHOCLES:	Yes. We have been sent to the planet	Earth	to
steal	the	formula for the most significant and exciting
